# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode10.1
branches:
  only:
    - master
cache: bundler
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MobileForce.xcworkspace -scheme MobileForce-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
